### PR TITLE
Fixes clang-cl compilation issue

### PR DESCRIPTION
**Pull request by matbech**
Fixes issue https://github.com/microsoft/DirectXMath/issues/156

### CODE REVIEW

**Comment by walbourn** [comment]
What scenario is this that's failing?

**Comment by matbech** [comment]
> What scenario is this that's failing?

When winrt is used/included:
#include <winrt\base.h>
winrt\base.h includes directxmath.h from the SDK.

with the clang-cl as the compiler frontend.

**Comment by walbourn** [comment]
Which Windows SDK?

**Comment by matbech** [comment]
> Which Windows SDK?

The latest insider SDK: 10.0.25276.0

**Pull request closed without merging**
